services:
  service_users:
    build: ./service_users
    container_name: service_users
    environment:
      - PORT=8001
      - JWT_SECRET=dev_secret
    ports:
      - "8001:8001"

  service_orders:
    build: ./service_orders
    container_name: service_orders
    environment:
      - PORT=8002
      - JWT_SECRET=dev_secret
    ports:
      - "8002:8002"

  api_gateway:
    build: ./api_gateway
    container_name: api_gateway
    environment:
      - PORT=8000
      - JWT_SECRET=dev_secret
      - USERS_URL=http://service_users:8001
      - ORDERS_URL=http://service_orders:8002
    ports:
      - "8000:8000"
    depends_on:
      - service_users
      - service_orders
